### PR TITLE
Add missing cmocka to buildbot workers

### PR DESCRIPTION
**Pull request by flichtenheld**

### CODE REVIEW

**Comment by flichtenheld** [comment]
Tested on buildbot-host-staging.

**Comment by mattock** [comment]
Looks good except for removal of the alpine bootstrapping script. Having alpine tested was a feature request from dazo and I believe I implemented it in the previous hackathon. I think I got distracted by something else(tm) and the work was never 100% completed. That said, I think build-testing OpenVPN 2 (which is easily containerizable) in Alpine would be useful. Thoughts?

**Comment by flichtenheld** [comment]
Okay, I will check whether I can get the alpine one working

**Comment by mattock** [comment]
> Okay, I will check whether I can get the alpine one working

:+1:

**Comment by flichtenheld** [comment]
alpine is fixed

**Comment by mattock** [comment]
Looks good, thanks!

**Pull request merged**
